#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20

postgres:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    default-auto-commit: false
#    h2.console.enabled: true
#h2:
#  datasource:
#    jdbcUrl: jdbc:h2:./src/main/resources/db/h2
#    username: sa
#    password:
#    default-auto-commit: false
#    h2.console.enabled: true

firebird:
  datasource:
    jdbcUrl: jdbc:firebirdsql://localhost:3050/c:/db/report_stom.fdb?lc_ctype=WIN1251
    username: SYSDBA
    password: masterkey
    default-auto-commit: false

  # Jackson Serialization Issue Resolver
  #  jackson:
  #    visibility:
  #      field: any
  #      getter: none
  #      setter: none
  #      is-getter: none

# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
#  cache:
#    cache-names: users
#    caffeine.spec: maximumSize=1,expireAfterAccess=60s

#logging:
#  level:
#    root: WARN
#    ru.javaops.topjava: DEBUG
#    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: ERROR
    ru.bstrdn: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: /Users/leo/app.log
